"use client";

import { useCallback, useEffect, useId, useRef, useState } from "react";
import { Activity, ArrowDownRight, ArrowUpRight, BookOpen, ChartNoAxesCombined, Check, ChevronDown, ChevronRight, CircleAlert, CircleHelp, Clock3, Database, Download, ExternalLink, FileSearch, Layers3, LoaderCircle, MessageSquare, RefreshCw, Send, ShieldCheck, Sparkles, X } from "lucide-react";
import { INDICES, type Bar, type Evidence, type Insight, type ModelResult, type Report, type ResearchRequest, type ResearchFollowup, type Trace } from "../lib/market/types";
import { fixed, pct } from "../lib/market/engine";
import { reportMarkdown, reportJSON } from "../lib/market/export";
import { researchPlan } from "../lib/market/plan";

type Config={fuyaoConfigured:boolean;modelConfigured:boolean;model:string;latestCompletedDate:string;today:string;calendarStatus:string;replay:{from:string;to:string}};
type Followup=ResearchFollowup;
const DEFAULT:ResearchRequest={index:"000001.SH",window:20,asOf:"2026-08-31",mode:"replay"};
const modelLabel=(model:ModelResult)=>model.status==="generated"?"DeepSeek 证据解读":model.status==="refused"?"研究边界提示":"规则解读";

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){
 const dialog=useRef<HTMLDialogElement>(null),id=useId();
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
 return <dialog ref={dialog} className="modal" aria-labelledby={id} onClose={onClose} onClick={event=>{if(event.target===event.currentTarget)onClose();}}><div className="modal-heading"><h2 id={id}>{title}</h2><button className="icon-button" aria-label="关闭" onClick={onClose}><X size={20}/></button></div><div className="modal-body">{children}</div></dialog>;
}

function PriceChart({bars,name}:{bars:Bar[];name:string}){
 const [hover,setHover]=useState<number|null>(null),id=useId().replaceAll(":","");
 if(bars.length<2)return <div className="chart-empty">历史数据不足，暂不绘制价格曲线。</div>;
 const width=760,height=205,left=58,right=14,top=15,bottom=25,values=bars.map(b=>b.close_price),low=Math.min(...values),high=Math.max(...values),padding=(high-low)*.17||high*.01,min=low-padding,max=high+padding;
 const x=(i:number)=>left+i/(bars.length-1)*(width-left-right),y=(n:number)=>top+(max-n)/(max-min)*(height-top-bottom);
 const points=bars.map((b,i)=>`${x(i)},${y(b.close_price)}`).join(" "),path=bars.map((b,i)=>`${i?"L":"M"}${x(i)} ${y(b.close_price)}`).join(" ");
 const picked=hover===null?bars.at(-1)!:bars[hover];
 return <div className="price-chart"><div className="chart-legend"><span><i/>收盘价 <b>{name}</b></span><span className="chart-picked">{picked.date} <strong>{fixed(picked.close_price)} 点</strong></span></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${name}从${bars[0].date}到${bars.at(-1)!.date}的收盘价格曲线`} onMouseLeave={()=>setHover(null)} onMouseMove={event=>{const rect=event.currentTarget.getBoundingClientRect();setHover(Math.max(0,Math.min(bars.length-1,Math.round(((event.clientX-rect.left)/rect.width*width-left)/(width-left-right)*(bars.length-1)))));}} onTouchMove={event=>{const touch=event.touches[0],rect=event.currentTarget.getBoundingClientRect();setHover(Math.max(0,Math.min(bars.length-1,Math.round(((touch.clientX-rect.left)/rect.width*width-left)/(width-left-right)*(bars.length-1)))));}}><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#0b8d8b" stopOpacity=".17"/><stop offset="100%" stopColor="#0b8d8b" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3].map(i=>{const value=min+(max-min)*i/3;return <g key={i}><line x1={left} x2={width-right} y1={y(value)} y2={y(value)} stroke="#e8eef2" strokeDasharray="3 4"/><text x={left-9} y={y(value)+4} textAnchor="end" fill="#8395a1" fontSize="11">{value.toFixed(0)}</text></g>;})}<path d={`${path} L${x(bars.length-1)} ${height-bottom} L${left} ${height-bottom} Z`} fill={`url(#${id})`}/><polyline points={points} fill="none" stroke="#078789" strokeWidth="2.4" strokeLinejoin="round" strokeLinecap="round"/>{hover!==null&&<g><line x1={x(hover)} x2={x(hover)} y1={top} y2={height-bottom} stroke="#91afb9" strokeDasharray="3 3"/><circle cx={x(hover)} cy={y(picked.close_price)} r="4" fill="#fff" stroke="#078789" strokeWidth="2"/></g>}<text x={left} y={height-3} fill="#8395a1" fontSize="11">{bars[0].date.slice(5)}</text><text x={width-right} y={height-3} textAnchor="end" fill="#8395a1" fontSize="11">{bars.at(-1)!.date.slice(5)}</text></svg></div>;
}

function EvidenceLinks({ids,onSelect}:{ids:string[];onSelect:(id:string)=>void}){
 return <span className="evidence-links">{ids.map(id=><button key={id} onClick={()=>onSelect(id)} aria-label={`查看${id}证据`}>[{id}]</button>)}</span>;
}
function download(name:string,content:string,type="text/markdown;charset=utf-8"){
 const url=URL.createObjectURL(new Blob([content],{type})),link=document.createElement("a");link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}


export default function MarketWorkspace(){
 const [config,setConfig]=useState<Config|null>(null),[draft,setDraft]=useState<ResearchRequest>(DEFAULT),[report,setReport]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [errorTraces,setErrorTraces]=useState<Trace[]>([]),[selectedEvidence,setSelectedEvidence]=useState<string|null>(null),[methodOpen,setMethodOpen]=useState(false),[sourcesOpen,setSourcesOpen]=useState(false),[planOpen,setPlanOpen]=useState(false);
 const [question,setQuestion]=useState(""),[followups,setFollowups]=useState<Followup[]>([]),[followBusy,setFollowBusy]=useState(false),[followError,setFollowError]=useState("");
 const abort=useRef<AbortController|null>(null),followAbort=useRef<AbortController|null>(null),reportRef=useRef<Report|null>(null);
 const runResearch=useCallback(async(request:ResearchRequest)=>{
  abort.current?.abort();followAbort.current?.abort();setFollowBusy(false);const controller=new AbortController();abort.current=controller;setBusy(true);setError("");setErrorTraces([]);
  try{const response=await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(request),signal:controller.signal});const data=await response.json() as {report:Report;error?:string;traces?:Trace[]};if(!response.ok)throw Object.assign(new Error(data.error||"研究未完成，请重试。"),{traces:data.traces||[]});
   const next=data.report as Report;setReport(next);reportRef.current=next;setFollowups([]);setFollowError("");setQuestion("");return next;
  }catch(e){if(e instanceof Error&&e.name==="AbortError")return null;setError(e instanceof Error?e.message:"网络请求失败，请重试。");setErrorTraces((e as {traces?:Trace[]}).traces||[]);return null;}finally{if(abort.current===controller)setBusy(false);}
 },[]);
 useEffect(()=>{let active=true;fetch("/api/config").then(async r=>await r.json() as Config).then((c)=>{if(!active)return;setConfig(c);const next:ResearchRequest={...DEFAULT,mode:c.fuyaoConfigured?"fuyao":"replay",asOf:c.fuyaoConfigured?c.latestCompletedDate:c.replay.to};setDraft(next);void runResearch(next);}).catch(()=>{if(active){setError("连接状态读取失败，可先尝试官方历史回放。");}});return()=>{active=false;abort.current?.abort();};},[runResearch]);
 useEffect(()=>{
  type Tool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};
  const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const tools:Tool[]=[{name:"get_market_report",title:"读取当前市场复盘",description:"读取页面当前报告的日期、状态、覆盖和证据，不重新取数。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>{const r=reportRef.current;return r?{asOf:r.asOf,index:r.indexName,regime:r.regime,coverage:r.coverage,evidence:r.evidence.map(e=>({id:e.id,status:e.status,observation:e.observation}))}:{status:"no_report"};}},{name:"run_market_research",title:"生成市场复盘",description:"选择指数、窗口、截至日和来源，执行取数并更新当前报告。",inputSchema:{type:"object",properties:{index:{type:"string",enum:INDICES.map(i=>i.code)},window:{type:"integer",enum:[20,60]},asOf:{type:"string",pattern:"^\\d{4}-\\d{2}-\\d{2}$"},mode:{type:"string",enum:["replay","official","fuyao"]}},required:["index","window","asOf","mode"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input)=>{const value=input as ResearchRequest;if(!value||!INDICES.some(i=>i.code===value.index)||![20,60].includes(value.window)||!["replay","official","fuyao"].includes(value.mode)||!/^\d{4}-\d{2}-\d{2}$/.test(value.asOf))throw new Error("Invalid research parameters");setDraft(value);const r=await runResearch(value);if(!r)throw new Error("Research failed");await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {reportId:r.id,asOf:r.asOf,index:r.indexName,regime:r.regime};}}];
  for(const tool of tools)try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[runResearch]);
 const changeMode=(mode:ResearchRequest["mode"])=>setDraft(current=>({...current,mode,asOf:mode==="fuyao"?(config?.latestCompletedDate||current.asOf):(config?.replay.to||DEFAULT.asOf)}));
 const ask=async(text:string)=>{
  if(!report||followBusy||text.trim().length<2)return;const reportId=report.id,controller=new AbortController();followAbort.current=controller;setFollowBusy(true);setFollowError("");
  try{const response=await fetch("/api/followup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({request:report.request,snapshotFingerprint:report.snapshotFingerprint,question:text.trim()}),signal:controller.signal});const data=await response.json() as Omit<Followup,"question">&{error?:string};if(!response.ok)throw new Error(data.error||"继续研究失败。");if(reportRef.current?.id!==reportId)return;setFollowups(current=>[...current,{question:text.trim(),...data}]);setQuestion("");}catch(e){if(e instanceof Error&&e.name==="AbortError")return;if(reportRef.current?.id===reportId)setFollowError(e instanceof Error?e.message:"继续研究失败，请重试。");}finally{if(reportRef.current?.id===reportId)setFollowBusy(false);}
 };
 const evidence=report?.evidence.find(e=>e.id===selectedEvidence),dirty=!!report&&(["index","window","asOf","mode","question"] as const).some(key=>draft[key]!==report.request[key]),positive=(value:number|null|undefined)=>value!==null&&value!==undefined&&value>=0;
 return <div className="workspace">
  <aside className="sidebar"><div className="brand"><span className="brand-mark"><Activity size={22}/></span><span>观市<small>MARKET LENS</small></span></div><div className="side-label">研究工作台</div><button className="nav-item active" aria-label="市场复盘" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}><ChartNoAxesCombined size={18}/>市场复盘</button><a className="nav-item" href="#evidence" aria-label="证据档案"><FileSearch size={18}/>证据档案</a><button className="nav-item" aria-label="研究方法" onClick={()=>setMethodOpen(true)}><BookOpen size={18}/>研究方法</button><div className="sidebar-bottom"><div className="connection-label">{config?.fuyaoConfigured?<Check size={13}/>:<Database size={13}/>} {config?.fuyaoConfigured?"金融数据已连接":"官方历史数据"}</div><small>{config?.modelConfigured?"DeepSeek 已配置":"规则解读可用"}</small><button onClick={()=>setSourcesOpen(true)}>查看连接状态 <ChevronRight size={12}/></button></div></aside>
  <div className="main-shell"><header className="topbar"><div><span className="breadcrumb">研究工作台</span><span className="crumb-divider">/</span>市场复盘</div><button className="top-note text-button" onClick={()=>setSourcesOpen(true)}><Database size={14}/>数据与模型连接</button></header>
   <main><div className="page-heading"><div><div className="eyebrow">MARKET BRIEFING</div><h1>读懂市场，先看证据。</h1><p>梳理市场状态、主要矛盾，以及判断可能改变的条件。</p></div><div className="export-actions"><button className="secondary" disabled={!report||busy||followBusy} onClick={()=>report&&download(`观市-${report.indexName}-${report.asOf}.md`,reportMarkdown(report,followups))}><Download size={15}/>导出复盘</button><button className="secondary" disabled={!report||busy||followBusy} onClick={()=>report&&download(`观市-${report.indexName}-${report.asOf}.json`,reportJSON(report,followups),"application/json")}>导出 JSON</button></div></div>
    <form className="research-bar" onSubmit={e=>{e.preventDefault();void runResearch(draft);}}><label>研究指数<select value={draft.index} onChange={e=>setDraft({...draft,index:e.target.value})}>{INDICES.map(i=><option key={i.code} value={i.code}>{i.name}</option>)}</select></label><label>观察窗口<select value={draft.window} onChange={e=>setDraft({...draft,window:Number(e.target.value) as 20|60})}><option value={20}>近20个交易日</option><option value={60}>近60个交易日</option></select></label><label>截至交易日<input type="date" aria-label="截至交易日" value={draft.asOf} max={draft.mode==="fuyao"?config?.latestCompletedDate:config?.today} min={draft.mode==="replay"?"2026-06-01":undefined} required onChange={e=>setDraft({...draft,asOf:e.target.value})}/></label><label>数据来源<select value={draft.mode} onChange={e=>changeMode(e.target.value as ResearchRequest["mode"])}><option value="fuyao" disabled={!config?.fuyaoConfigured}>扶摇金融接口</option><option value="official">上交所历史接口</option><option value="replay">官方历史缓存回放</option></select></label><button className="primary" disabled={busy} type="submit">{busy?<LoaderCircle size={17} className="spin"/>:<Sparkles size={17}/>} {busy?"研究进行中":"生成复盘"}</button></form>
    {error&&<div className="error-banner" role="alert"><CircleAlert size={18}/><div><strong>本次研究未完成</strong><p>{error}</p>{report&&<small>下方保留上一份有效结果，截至 {report.asOf}。</small>}</div><button className="text-button" onClick={()=>void runResearch(draft)}>重试</button></div>}
    {busy&&<div className="working-banner" role="status"><LoaderCircle size={16} className="spin"/>正在获取数据、核验日期与口径，并整理研究证据。{report&&<span>下方为上一份有效结果。</span>}</div>}
    {dirty&&!busy&&!error&&<div className="draft-notice">研究条件已修改，点击“生成复盘”更新结果。下方仍为 {report?.indexName} · {report?.asOf} 的报告。</div>}
    <section className="plan-panel"><button className="plan-toggle" aria-expanded={planOpen} onClick={()=>setPlanOpen(!planOpen)}><span><Layers3 size={16}/><strong>研究计划与执行记录</strong><span className="plan-summary">交易日 → 指数日线 → 指标核验 → 证据解读</span></span><span>{report&&!busy?`${report.traces.filter(t=>t.status==="success"||t.status==="cached").length}项完成`:"按实际返回记录"}<ChevronDown size={15} className={planOpen?"rotate":""}/></span></button>{planOpen&&<div className="trace-list"><div className="preflight-plan"><strong>待执行计划 · 随上方研究条件更新</strong><ol>{researchPlan(draft).map(step=><li key={step}>{step}</li>)}</ol></div><strong className="execution-label">{busy?"下方为上一份报告的执行记录":"报告实际执行记录"}</strong>{(errorTraces.length?errorTraces:report?.traces||[]).map((trace,i)=><div className="trace-row" key={`${trace.id}-${i}`}><span className={`trace-icon ${trace.status}`}>{trace.status==="failed"?<X size={13}/>:trace.status==="skipped"?<span>—</span>:<Check size={13}/>}</span><div><strong>{trace.tool}</strong><p>{trace.message}</p></div><span className="trace-duration">{trace.status==="cached"?"历史缓存":trace.status==="skipped"?"未执行":`${trace.durationMs} ms`}</span></div>)}{!report&&!errorTraces.length&&<p className="body-muted">先确定已完成交易日，再获取所选指数及风格比较指数的历史日线；数据核验后计算指标，最后生成解读。市场宽度只使用与研究日一致的完整快照。</p>}</div>}</section>
    {!report?<section className="panel"><div className="empty-state"><FileSearch size={38}/><h2>{busy?"正在建立本次研究的证据链":"从一个研究问题开始"}</h2><p>每项结论将展示原始字段、统计口径和时间范围。数据缺失时会保留判断。</p></div></section>:<>
     <div className="report-meta"><span><Clock3 size={13}/>截至 {report.asOf} <span className="meta-separator">·</span>{report.indexName}<span className="meta-separator">·</span>近{report.request.window}个交易日</span><span className={`tag ${report.request.mode==="fuyao"?"teal":"amber"}`}>{report.modeLabel}</span></div>
     {report.warnings.length>0&&<details className="data-notice"><summary><CircleAlert size={14}/><span>{report.warnings[0]}</span>{report.warnings.length>1&&<b>+{report.warnings.length-1}</b>}</summary>{report.warnings.slice(1).map((w,i)=><p key={i}>{w}</p>)}</details>}
     <div className="content-grid main-results"><div className="main-column"><section className="panel overview-panel"><div className="panel-heading"><span><span className="section-num">01</span>市场状态</span><button className="tag neutral" onClick={()=>setMethodOpen(true)}>置信度（证据支持度）：{report.coverage.confidence}<CircleHelp size={12}/></button></div><div className="state-line"><h2>{report.regime}</h2><span className="tag teal">{report.evidence.find(e=>e.id==="breadth")?.status==="available"?"含同日宽度":"指数层面观察"}</span></div><p className="state-description">{report.summary}</p><div className="key-metrics"><div><span>截至日收盘</span><strong>{fixed(report.metrics.close)}<small>点</small></strong><em className={positive(report.metrics.dailyReturn)?"rise":"fall"}>单日 {pct(report.metrics.dailyReturn)}</em></div><div><span>区间收益</span><strong className={positive(report.metrics.windowReturn)?"rise":"fall"}>{pct(report.metrics.windowReturn)}</strong><em>{report.request.window}个收盘到收盘交易日</em></div><div><span>成交活跃度 <button aria-label="查看成交活跃度口径" onClick={()=>setSelectedEvidence("activity")}><CircleHelp size={12}/></button></span><strong>{report.metrics.activityRatio?.toFixed(2)||"—"}<small>倍</small></strong><em>近5日均额 / 近20日均额</em></div></div><PriceChart bars={report.bars} name={report.indexName}/><div className="chart-footnote"><span>MA20 <b>{fixed(report.metrics.ma20)}</b></span><span>MA60 <b>{fixed(report.metrics.ma60)}</b></span><span>均线仅描述历史结构</span></div></section>
       <section className="panel interpretation-panel"><div className="panel-heading"><span><span className="section-num">02</span>主要矛盾与研究判断</span><span className="tag neutral"><Sparkles size={12}/>{modelLabel(report.model)}</span></div>{report.model.status!=="generated"&&<p className="model-notice">{report.model.reason}</p>}{report.model.summary&&<p className="ai-summary">{report.model.summary}</p>}<div className="interpretation-grid"><div><h3><span className="support-mark"/>支持证据</h3>{report.supports.map((item,i)=><div className="insight" key={i}><p>{item.text}</p><EvidenceLinks ids={item.evidenceIds} onSelect={setSelectedEvidence}/></div>)}</div><div><h3><span className="conflict-mark"/>冲突与未决问题</h3>{report.conflicts.map((item,i)=><div className="insight" key={i}><p>{item.text}</p><EvidenceLinks ids={item.evidenceIds} onSelect={setSelectedEvidence}/></div>)}</div></div>{report.model.insights&&<div className="model-insights">{report.model.insights.map((item,i)=><div className="insight" key={i}><span className="tiny-label">{item.kind==="inference"?"AI 归纳":"AI 不确定性"}</span><p>{item.text}</p><EvidenceLinks ids={item.evidenceIds} onSelect={setSelectedEvidence}/></div>)}</div>}</section>
      </div><aside className="right-column"><section className="panel watch-panel"><div className="panel-heading"><span><span className="section-num">03</span>什么会改变判断</span><RefreshCw size={15}/></div>{report.conditions.map((c,i)=><div className="watch-item" key={c.title}><span className="watch-number">0{i+1}</span><div><h3>{c.title}</h3><p>{c.detail}</p><EvidenceLinks ids={c.evidenceIds} onSelect={setSelectedEvidence}/></div></div>)}</section><section className="panel coverage-panel"><div className="panel-heading"><span><ShieldCheck size={16}/>本次证据覆盖</span><span className="coverage-count">{report.coverage.available}<small> / {report.coverage.total}</small></span></div><div className="coverage-segments">{report.evidence.map(e=><span key={e.id} className={e.status==="available"?"filled":""} title={e.dimension}/>)}</div><div className="coverage-list">{report.evidence.map(e=><button key={e.id} onClick={()=>setSelectedEvidence(e.id)}><span>{e.status==="available"?<Check size={13}/>:<span className="missing-dash">—</span>}{e.dimension}</span><span>{e.status==="available"?"已核验":"未覆盖"}</span></button>)}</div><p className="coverage-note">{report.coverage.explanation}</p></section><section className="scope-note"><CircleHelp size={16}/><p>指数表现、全市场参与程度与未来涨跌，是不同的问题。当前结论只覆盖已取得的证据。</p></section></aside></div>
     <section className="panel evidence-section" id="evidence"><div className="panel-heading"><span><span className="section-num">04</span>事实与证据档案</span><span className="small-muted">点击查看来源、原始字段与计算过程</span></div><div className="evidence-grid">{report.evidence.map((e,i)=><button key={e.id} className={`evidence-card ${e.status==="missing"?"missing":""}`} onClick={()=>setSelectedEvidence(e.id)}><div className="evidence-card-top"><span>{e.dimension}</span><span className="evidence-index">E0{i+1}</span></div><strong>{e.displayValue}</strong><p>{e.status==="available"?e.interpretation:e.observation}</p><div className="evidence-card-bottom"><span>{e.scope}</span><ChevronRight size={14}/></div></button>)}</div></section>
     <section className="panel followup-section"><div className="panel-heading"><span><MessageSquare size={16}/>继续研究</span><span className="small-muted">沿用本次指数、区间与证据口径</span></div><div className="suggestion-chips">{["科创与大盘表现有何差异？","哪些风险变量值得继续核验？","当前判断有哪些证据缺口？"].map(text=><button key={text} onClick={()=>void ask(text)} disabled={followBusy||busy}>{text}</button>)}</div><div className="conversation" aria-live="polite">{followups.map((f,i)=><article key={i} className="followup-result"><h3><MessageSquare size={14}/>{f.question}</h3><span className="tag neutral">{modelLabel(f.model)} · 截至 {f.asOf}</span><p>{f.answer}</p>{f.insights.map((item,j)=><div className="insight" key={j}><p>{item.text}</p><EvidenceLinks ids={item.evidenceIds} onSelect={setSelectedEvidence}/></div>)}{f.model.status==="failed"&&<p className="model-notice">{f.model.reason}</p>}</article>)}</div>{followError&&<p role="alert" className="error-text">{followError}</p>}<form className="question-form" onSubmit={e=>{e.preventDefault();void ask(question);}}><label className="sr-only" htmlFor="research-question">继续研究的问题</label><input id="research-question" placeholder="围绕风格、风险变量或证据继续追问…" value={question} maxLength={500} minLength={2} onChange={e=>setQuestion(e.target.value)} disabled={followBusy||busy}/><button className="primary" type="submit" disabled={followBusy||busy||question.trim().length<2}>{followBusy?<LoaderCircle size={16} className="spin"/>:<Send size={16}/>}<span>{followBusy?"研究中":"提问"}</span></button></form></section>
     <div className="report-bottom"><span>生成于 {new Date(report.generatedAt).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",hour12:false})}</span><span>{report.model.status==="generated"?`${report.model.model} · ${(report.model.durationMs/1000).toFixed(1)}秒${report.model.tokens?` · ${report.model.tokens} tokens`:""}`:"透明规则 · 可复算指标"}</span></div>
    </>}
    <footer>市场状态研究仅用于信息理解，不构成确定性涨跌预测、收益承诺或买卖建议。</footer>
   </main></div>
  {selectedEvidence&&evidence&&<Modal title={`${evidence.dimension} · 证据详情`} onClose={()=>setSelectedEvidence(null)}><span className={`tag ${evidence.status==="available"?"teal":"amber"}`}>{evidence.status==="available"?"事实可复算":"证据未覆盖"}</span><h3 className="evidence-detail-value">{evidence.displayValue}</h3><p>{evidence.observation}</p><dl className="evidence-definition"><dt>研究范围</dt><dd>{evidence.scope}</dd><dt>截至日期</dt><dd>{evidence.asOf}</dd><dt>统计口径</dt><dd>{evidence.formula}</dd><dt>单位</dt><dd>{evidence.unit||"不适用"}</dd><dt>原始字段</dt><dd>{Object.entries(evidence.rawFields).map(([key,value])=><div key={key}><code>{key}</code> ← {value}</div>)}</dd><dt>采集时间</dt><dd>{evidence.retrievedAt?new Date(evidence.retrievedAt).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",hour12:false}):"未取得"}</dd><dt>数据来源</dt><dd>{evidence.sourceUrl?<a href={evidence.sourceUrl} target="_blank" rel="noreferrer">{evidence.source}<ExternalLink size={12}/></a>:"未接入"}</dd></dl><div className="detail-caveat"><CircleAlert size={16}/>{evidence.caveat}</div>{evidence.status==="available"&&<><details className="raw-details"><summary>查看请求与原始计算输入</summary><p className="endpoint-text">{evidence.endpoint}</p><pre>{JSON.stringify(evidence.inputs,null,2)}</pre></details><button className="secondary" onClick={()=>download(`证据-${evidence.id}-${evidence.asOf}.json`,JSON.stringify(evidence,null,2),"application/json")}><Download size={14}/>下载证据</button></>}</Modal>}
  {methodOpen&&<Modal title="研究方法与判断边界" onClose={()=>setMethodOpen(false)}><p>本产品先计算事实，再按公开规则归纳结构，最后由模型解释证据。阈值为产品启发式规则，未经收益预测校准。</p><div className="method-list"><section><h3>指数结构</h3><p>截至日收盘价同时高于MA20和MA60为上行结构；同时低于为下行结构；位于其间为结构分化。MA60需要至少60个有效交易日。</p></section><section><h3>成交活跃度</h3><p>近5日平均成交额÷近20日平均成交额。达到1.2倍为放大，低于或等于0.8倍为收缩。它不代表净资金流向。</p></section><section><h3>风格代理与波动</h3><p>比较科创50与沪深300在完全相同起止日的收益差。日波动为近20个日收益率的样本标准差，不年化、不预测。</p></section><section><h3>置信度（证据支持度）</h3><p>核心结构与目标日期满足时，7个维度中6–7项可计算为高，3–5项为中，其余为低；核心历史不足或行情早于目标日时降为低。该标签是覆盖提示，不是上涨概率。覆盖相同时，信号可以彼此冲突。</p></section><section><h3>时间与缺失</h3><p>观察窗口为20/60个收盘到收盘的交易日；计算均线需要的历史单独获取。盘中日线不纳入收盘研究，历史研究不混用当前快照。市场宽度要求完整分页及至少90%的有效行情覆盖；收盘后数据时间仍需核验。未接入新闻不能解释为没有重要事件。</p></section><section><h3>模型职责</h3><p>模型只解释程序计算的已有证据，不修改指标、来源和结构标签；超时、结构异常、无效证据引用时回退为规则解读。</p></section></div></Modal>}
  {sourcesOpen&&<Modal title="数据与模型连接" onClose={()=>setSourcesOpen(false)}><div className="source-item"><Database size={20}/><div><h3>扶摇金融数据</h3><p>{config?.fuyaoConfigured?`已配置 · 交易日历${config.calendarStatus==="available"?"可用":"待核验"} · 最近已完成交易日 ${config.latestCompletedDate}`:"尚未配置，可先使用官方历史数据。"}</p><a href="https://fuyao.aicubes.cn/docs/quickstart/" target="_blank" rel="noreferrer">官方接入说明 <ExternalLink size={12}/></a></div></div><div className="source-item"><BookOpen size={20}/><div><h3>上海证券交易所</h3><p>公开月报历史接口与官方响应缓存。缓存范围2026-06-01至2026-08-31，包含4个指数与沪市分板估值。月报存在发布延迟。</p><a href="https://www.sse.com.cn/aboutus/publication/monthly/index/" target="_blank" rel="noreferrer">官方统计月报 <ExternalLink size={12}/></a></div></div><div className="source-item"><Sparkles size={20}/><div><h3>DeepSeek</h3><p>{config?.modelConfigured?`已配置 · ${config.model}；每次调用仍需通过输出核验。`:"尚未配置。取数与指标仍可使用，报告将明确标注为规则解读。"}</p></div></div><div className="detail-caveat"><ShieldCheck size={16}/>连接凭证保存在服务端，不随报告、导出文件或浏览器页面返回。</div></Modal>}
 </div>;
}
